language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install sphinx
  - pip install tox
script:
  - pytest
  - tox
  - coverage run --source PynPoint -m pytest
  - sphinx-apidoc -o docs/ PynPoint