language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install tox
  - pip install coverage
  - pip install sphinx
script:
  - make test
  - make test-all
  - make coverage
  - make docs
notifications:
  email:
    recipients:
      - tomas.stolker@phys.ethz.ch
    on_success: change
    on_failure: always