language: python

matrix:
    include:

        # - os: osx
        #   language: generic
        #   env:
        #     - TOXENV=py27
        #     - NUMBA_DISABLE_JIT=1
        #
        # - os: osx
        #   language: generic
        #   env:
        #     - TOXENV=py36
        #     - NUMBA_DISABLE_JIT=1

        - os: osx
          language: generic
          env:
            - PYTHON=3.7.0
            - TOXENV=py37
            - NUMBA_DISABLE_JIT=1

        # - os: linux
        #   python: 2.7
        #   env:
        #     - TOXENV=py27
        #     - NUMBA_DISABLE_JIT=1

        # - os: linux
        #   python: 3.6
        #   env:
        #     - TOXENV=py36
        #     - NUMBA_DISABLE_JIT=1

        # - os: linux
        #   python: 3.7
        #   dist: xenial
        #   sudo: true
        #   env:
        #     - TOXENV=py37
        #     - NUMBA_DISABLE_JIT=1

before_install:
  - echo $TRAVIS_OS_NAME
  - echo $PYTHON
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" && "$PYTHON" == "3.7.0" ]; then
      brew update
      brew upgrade openssl readline pyenv
      brew install pyenv-virtualenv
      python --version
      pyenv install $PYTHON
      export PYENV_VERSION=$PYTHON
      python --version
      ls -l .pyenv
      ls -l .pyenv/shims
      # export PATH="/Users/travis/.pyenv/shims:${PATH}"
      pyenv virtualenv venv
      pyenv activate venv
      python --version
    fi

install:
  - python -m pip install -U pip
  - pip install numpy
  - pip install enum34
  - pip install -r requirements.txt
  - pip install tox
  - pip install coverage
  - pip install coveralls
  - pip install sphinx
  - pip install sphinx_rtd_theme

before_script:
  - mkdir $HOME/.matplotlib
  - "echo 'backend: Agg' > $HOME/.matplotlib/matplotlibrc"

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false
