language: python
os:
  - linux
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install tox
  - pip install coverage
  - pip install sphinx
script:
  - pytest
  - tox
  - coverage run --source PynPoint -m pytest
  - sphinx-apidoc -o docs/ PynPoint