language: python
matrix:
    include:
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: linux
          python: 2.7
          env: TOXENV=py27
install:
  - pip2 install numpy
  - pip2 install enum34
  - pip2 install -r requirements.txt
  - pip2 install tox
  - pip2 install coverage
  - pip2 install sphinx
  - pip2 install codecov
  - pip2 install sphinx_rtd_theme
after_install:
  - mkdir $HOME/.matplotlib
  - "echo 'backend: Agg' > $HOME/.matplotlib/matplotlibrc"
script:
  - make test
  - make test-all
  - make coverage
  - make docs
after_success:
  - codecov
notifications:
  email: false
