language: python
matrix:
    include:
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: linux
          python: 2.7
          env: TOXENV=py27
# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
#   - pip2 install virtualenv
#   - virtualenv venv -p python2
#   - source venv/bin/activate
install:
  - pip2 install numpy
  - pip2 install enum34
  - pip2 install -r requirements.txt
  - pip2 install tox
  - pip2 install coverage
  - pip2 install sphinx
  - pip2 install codecov
  - pip2 install sphinx_rtd_theme
before_script:
  - mkdir $HOME/.matplotlib
  - "echo 'backend: Agg' > $HOME/.matplotlib/matplotlibrc"
script:
  - make test
  - make test-all
  - make coverage
  - make docs
after_success:
  - codecov
notifications:
  email: false
