language: python
# python:
#   - "2.7"
matrix:
    include:
        - os: osx
          language: generic
before_install:
  - brew unlink python
  - brew update
  - brew install python2 --framework
  - ls -a $HOME
  - ls -a $HOME/.matplotlib
  - echo 'backend: Agg' >> $HOME/.matplotlib/matplotlibrc
  - virtualenv venv -p python2
  - source venv/bin/activate
install:
  - pip2 install numpy
  - pip2 install -r requirements.txt
  - pip2 install tox
  - pip2 install coverage
  - pip2 install sphinx
before_script:
  - export OMP_NUM_THREADS=1
script:
  - make test
  - make test-all
  - make coverage
  - make docs
notifications:
  email:
    recipients:
      - tomas.stolker@phys.ethz.ch
    on_success: always
    on_failure: always