language: python
# python:
#   - "2.7"
matrix:
    include:
        - os: osx
          language: generic
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python2 --framework; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
  - pip2 install numpy
  - pip2 install -r requirements.txt
  - pip2 install tox
  - pip2 install coverage
  - pip2 install sphinx
before_script:
  - export OMP_NUM_THREADS=1
script:
  - make test
  - make test-all
  - make coverage
  - make docs
notifications:
  email:
    recipients:
      - tomas.stolker@phys.ethz.ch
    on_success: always
    on_failure: always