language: python

matrix:
    include:

        - os: osx
          language: generic
          env:
            - TOXENV=py27
            - NUMBA_DISABLE_JIT=1

        - os: osx
          language: generic
          env:
            - TOXENV=py36
            - NUMBA_DISABLE_JIT=1

        - os: osx
          language: generic
          env:
            - PYTHON=3.7.0
            - TOXENV=py37
            - NUMBA_DISABLE_JIT=1

        - os: linux
          python: 2.7
          env:
            - TOXENV=py27
            - NUMBA_DISABLE_JIT=1

        - os: linux
          python: 3.6
          env:
            - TOXENV=py36
            - NUMBA_DISABLE_JIT=1

        # - os: linux
        #   python: 3.7
        #   dist: xenial
        #   sudo: true
        #   env:
        #     - TOXENV=py37
        #     - NUMBA_DISABLE_JIT=1

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "osx" ] && [ $PYTHON == "3.7.0" ]; then
      brew install pyenv-virtualenv
      pyenv install $PYTHON
      pyenv which python
      export PYENV_VERSION=$PYTHON
      pyenv which python
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
      pyenv which python
      pyenv virtualenv $PYTHON venv
      pyenv which python
      pyenv activate venv
      pyenv which python
    fi

install:
  - pip install -r requirements.txt
  - pip install tox
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false
